services:
    oai-vnf:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-vnf
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --nfapi VNF
            NFAPI_TRACE_LEVEL: info
        volumes:
            - ../../conf_files/gnb-vnf.sa.band77.162prb.nfapi.4x4.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 15s
            timeout: 5s
            retries: 5
    oai-pnf:
        image: ${REGISTRY:-oaisoftwarealliance}/${GNB_IMG:-oai-gnb}:${TAG:-develop}
        network_mode: "host"
        container_name: oai-pnf
        cap_drop:
            - ALL
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        environment:
            TZ: Europe/Paris
            USE_ADDITIONAL_OPTIONS: --nfapi PNF
            NFAPI_TRACE_LEVEL: info
        volumes:
            - ../../conf_files/gnb-pnf.band77.usrpn310.4x4.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 15s
            timeout: 5s
            retries: 5
